on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
    - gh-pages
name: Update pages
jobs:
  generate:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup environment
      run: npm install
    - name: checkout webref repo
      run: git clone --depth 1 -b main https://github.com/w3c/webref.git
    - name: Generate pages
      run: node _tools/generate-pages.js
    - name: Commit updates
      run: |
        git config user.name "fetch-info bot"
        git config user.email "<>"
        git add -A
        git commit -m "Automatic update" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: "gh-pages"
